export type IconProps = React.SVGAttributes<SVGElement>;

export { default as ArrowLeftOnRectangle } from "./arrow-left-on-rectangle";
export { default as Bars3 } from "./bars-3";
export { default as CheckCircle } from "./check-circle";
export { default as ExclamationTriangle } from "./exclamation-triangle";
export { default as Eye } from "./eye";
export { default as EyeSlash } from "./eye-slash";
export { default as Github } from "./github";
export { default as Google } from "./google";
export { default as Info } from "./info";
export { default as LoadingCircle } from "./loading-circle";
export { default as LoadingDots } from "./loading-dots";
export { default as LoadingSpinner } from "./loading-spinner";
export { default as PencilSquare } from "./pencil-square";
export { default as QuestionMarkCircle } from "./question-mark-circle";
export { default as Squares2x2 } from "./squares-2x2";
export { default as UserPlus } from "./user-plus";
export { default as XCircle } from "./x-circle";
export { default as X } from "./x-mark";
