import Provider from "@/components/provider";
import "@/styles/tailwind.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";

type Props = {
  children: React.ReactNode;
};

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="pt-BR">
      <body className={raleway.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
